name: C++ application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_CONFIGURATION: Release

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      shell: cmd 
      run: ${{ '"C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\Tools\VsDevCmd.bat" && cd Chibiviewer && mkdir build && cl ChibiViewer.cpp /EHsc /std:c++14 /link user32.lib gdi32.lib gdiplus.lib shlwapi.lib ole32.lib shell32.lib /out:build\ChibiViewer.exe' }}
    - name: Upload Chibiviewer
      uses: actions/upload-artifact@v4
      with:
        name: Chibiviewer
        path: Chibiviewer/build/